name: autotest
description: auotest
author:
  name: Reverb Designs
  email: jordybell@gmail.com
  url: 'https://ReverbDesigns.com'
copyright: 2015 Reverb Designs
url: 'htps://reverbdesigns.com/autocode/'
imports:
  crystal/php: ~0.3.2
outputs:
  - generator: php.ConfigGenerator
    spec:
      register_globals: false
      include_path: /usr/local
