name: autotest
description: auotest
author:
  name: Reverb Designs
  email: jordybell@gmail.com
  url: 'https://ReverbDesigns.com'
copyright: 2015 Reverb Designs
url: 'htps://reverbdesigns.com/autocode/'
imports:
  crystal/handlebars: ~0.4.0
  crystal/npm: ~0.4.0
outputs:
  - generator: npm.PackageGenerator
    spec:
      name: myapp
      version: 1.0.0
      description: "myapp's description"
      dependencies:
        express: ~4.13.3
        grunt: ~0.4.5
        sequelize: ~3.5.1
