name: autotest
description: auotest
author:
  name: Reverb Designs
  email: jordybell@gmail.com
  url: 'https://ReverbDesigns.com'
copyright: 2015 Reverb Designs
url: 'htps://reverbdesigns.com/autocode/'
imports:
  crystal/bower: ~0.4.1
  crystal/handlebars: ~0.4.0
  crystal/angular: ~0.3.0
outputs:
  - generator: bower.ConfigGenerator
    spec:
      directory: app/components/
      analytics: false
      timeout: 120000
      registry:
        search:
          - 'http://localhost:8000'
          - 'https://bower.herokuapp.com'
  - generator: bower.PackageGenerator
    spec:
      name: blue-leaf
      version: 1.2.3
      description: Physics-like animations for pretty particles
      main:
        - js/motion.js
        - sass/motion.scss
      dependencies:
        get-size: ~1.2.2
        eventEmitter: ~4.2.11
      devDependencies:
        qunit: ~1.16.0
      moduleType:
        - amd
        - globals
        - node
      keywords:
        - motion
        - physics
        - particles
      authors:
        - 'Betty Beta <bbeta@example.com>'
      license: MIT
      ignore:
        - '**/.*'
        - node_modules
        - bower_components
        - test
        - tests
